-- Listar registros de tablas
SELECT * FROM COUNTRIES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM JOBS;
SELECT * FROM JOB_HISTORY;
SELECT * FROM LOCATIONS;
SELECT * FROM REGIONS;

-- Crear vista con nombres, apellido, edad, cargo y salario de empleado
CREATE VIEW vEMP_DETAILS
       AS
       SELECT 
            FIRST_NAME,
            LAST_NAME,
            EXTRACT(YEAR FROM SYSDATE)- EXTRACT(YEAR FROM HIRE_DATE) AS AGE, -- calcular años del empleado
            JOB_ID,
            SALARY 
       FROM EMPLOYEES;
  
-- Listar registros de VISTA
SELECT * FROM vEMP_DETAILS;

-- Listar EMPLEADOS con sus respectivos CARGOS y SALARIO
CREATE VIEW VEMP_JOBS_SALARY
    AS
    SELECT
       EMPLOYEES.FIRST_NAME,
       EMPLOYEES.LAST_NAME,
       EMPLOYEES.JOB_ID,
       JOBS.JOB_TITLE,
       EMPLOYEES.SALARY   
    FROM EMPLOYEES
         INNER JOIN JOBS
         ON EMPLOYEES.JOB_ID = JOBS.JOB_ID;
         
-- Listar registros VEMP_JOBS_SALARY
SELECT * FROM VEMP_JOBS_SALARY;

-- Crear VISTA para EMPLEADOS y sus respectivos departamentos
CREATE VIEW VEMP_DEPARTMENT
  AS
  SELECT
         EMPLOYEES.FIRST_NAME,
         EMPLOYEES.LAST_NAME,
         DEPARTMENTS.DEPARTMENT_NAME,
         EMPLOYEES.PHONE_NUMBER
         FROM EMPLOYEES
         INNER JOIN DEPARTMENTS
         ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

-- Listar VISTA de EMPLEADOS con sus respectivos DEPARTAMENTOS
SELECT * FROM VEMP_DEPARTMENT;

-- Crear VISTA para listar la cantidad de EMPLEADOS por DEPARTAMENTO
CREATE VIEW VEMP_QUANTITY_DEPARTMENT
  AS
  SELECT
       DEPARTMENTS.DEPARTMENT_NAME,
       COUNT(*) AS CANTIDAD
  FROM EMPLOYEES
       INNER JOIN DEPARTMENTS
       ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
  GROUP BY DEPARTMENTS.DEPARTMENT_NAME;
  
-- Listar registros de VISTA
SELECT * FROM VEMP_QUANTITY_DEPARTMENT;

-- Borrar vistar
DROP VIEW vEMP_DETAILS;
DROP VIEW VEMP_JOBS_SALARY;
DROP VIEW VEMP_DEPARTMENT;
DROP VIEW VEMP_QUANTITY_DEPARTMENT;
