-- Versión de base de datos instalada
SELECT * FROM V$VERSION;

-- Listar base de datos
SELECT * FROM V$DATABASE;

-- Ver instancia de base de datos
SELECT * FROM V$INSTANCE;

-- Ver listado de TABLESPACES
SELECT * FROM DBA_TABLESPACES;

-- Crear tablespace tbsDemo
CREATE TABLESPACE TBSDEMO
DATAFILE 'tbsdemo.dbf'
SIZE 200M;

-- Listar USUARIOS
SELECT * FROM DBA_USERS;

-- Listar USUARIOS de TABLESPACE USERS
SELECT  
    DEFAULT_TABLESPACE,
    USERNAME,
    ACCOUNT_STATUS,
    EXPIRY_DATE,
    AUTHENTICATION_TYPE
FROM DBA_USERS
WHERE DEFAULT_TABLESPACE = 'USERS';

-- Listar USUARIOS de TABLESPACE TBSDEMO
SELECT  
    DEFAULT_TABLESPACE,
    USERNAME,
    ACCOUNT_STATUS,
    EXPIRY_DATE,
    AUTHENTICATION_TYPE
FROM DBA_USERS
WHERE DEFAULT_TABLESPACE = 'TBSDEMO';

-- Crear usuario en TABLESPACE TBSDEMO
CREATE USER US_DEMO
IDENTIFIED BY Orcl1234
DEFAULT TABLESPACE TBSDEMO
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TBSDEMO;

-- Habilitar privilegios
GRANT CREATE SESSION TO US_DEMO;
GRANT CREATE TABLE TO US_DEMO;
GRANT CREATE VIEW TO US_DEMO;
GRANT CREATE PROCEDURE TO US_DEMO;
GRANT CREATE TRIGGER TO US_DEMO;
GRANT CREATE SEQUENCE TO US_DEMO;
GRANT CREATE JOB TO US_DEMO;
GRANT UNLIMITED TABLESPACE TO US_DEMO;

-- Listar los permisos de USUARIO SYS
SELECT * FROM SESSION_PRIVS;

-- Permitir ejecución de script
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
